3 10 gallery to albums
UB-ES-2023-B/b1-imageweb pull request #192
Opened 2023-12-09 16:03 UTC by danielaocampo2

En este pull request, he realizado los siguientes cambios:

- He implementado la funcionalidad completa para añadir fotos desde la galería a un álbum específico.

- Se ha implementado el manejo de errores para el caso en que las imágenes ya estén en el álbum correspondiente. Ahora, el se resalta las imágenes que generan el error e informa al usuario.

- También he gestionado la ocultación de la opción de eliminar mientras se añade una imagen, con el objetivo de prevenir posibles errores.

- Al escribir la primera letra en el desplegable, si existe un álbum que comienza con esa letra, se selecciona automáticamente. Sin embargo, este comportamiento se desactiva al presionar una letra que no corresponde a ningún álbum. Para reactivar la función, es necesario volver a desplegar la lista o buscar el álbum con el ratón. Cabe destacar que esta funcionalidad adicional no forma parte de los criterios de aceptación, pero se ha incluido como una mejora para facilitar la búsqueda.

- En el caso de nombres de álbumes muy extensos, se ha implementado una reducción a 100 caracteres, seguida de puntos suspensivos (...), para mejorar la visualización en el menú desplegable.

Espero tu respuesta para verificar que todo está

2023-12-09 21:57 UTC, IceFox72 requested changes
Te envié las cosas por Whatsapp

2023-12-10 13:29 UTC, danielaocampo2 commented
He solucionado el error de los álbumes duplicados

2023-12-12 00:55 UTC, danielaocampo2 commented
He realizado la nueva conexión con el backend para facilitar la renderización de las imágenes. 
Además,controlo la situación en la que se selecciona una foto que ya se encuentra en un álbum. En caso de que el usuario cambie de álbum, los errores asociados desaparecen automáticamente.

2023-12-12 17:57 UTC, IceFox72 approved these changes

2023-12-12 17:57 UTC, merged